# Generated by Django 2.0 on 2018-01-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Site name')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Site code')),
                ('url', models.URLField(help_text='URL link to DEFRA webpage', max_length=1000, verbose_name='DEFRA website link')),
                ('map_url', models.URLField(max_length=1000, verbose_name='Google maps url')),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
