# Generated by Django 2.0.4 on 2018-04-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='region',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
